import type { RequiredDataFromCollectionSlug } from 'payload'

export const openingHours: RequiredDataFromCollectionSlug<'opening-hours'>[] = [
  {
    tenant: 1,
    dayOfWeek: 'sunday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 1,
    dayOfWeek: 'monday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 1,
    dayOfWeek: 'tuesday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 1,
    dayOfWeek: 'wednesday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 1,
    dayOfWeek: 'thursday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 1,
    dayOfWeek: 'friday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 1,
    dayOfWeek: 'saturday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 2,
    dayOfWeek: 'sunday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 2,
    dayOfWeek: 'monday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 2,
    dayOfWeek: 'tuesday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 2,
    dayOfWeek: 'wednesday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 2,
    dayOfWeek: 'thursday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 2,
    dayOfWeek: 'friday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
  {
    tenant: 2,
    dayOfWeek: 'saturday',
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  },
]
