name: Build and Deploy Standalone

on:
  push:
    branches:
      - main # or your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node | pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js (standalone)
        env:
          DATABASE_URI: postgresql://postgres.zudswtpudtzzehieogcw:Nepal%40123@aws-0-eu-west-2.pooler.supabase.com:6543/postgres
          PAYLOAD_SECRET: 4ca13d993b1e2d789734dada
          NEXT_PUBLIC_SERVER_URL: https://ratosuryaonline.com
          CRON_SECRET: YOUR_CRON_SECRET_HERE
          PREVIEW_SECRET: YOUR_SECRET_HERE
        run: pnpm build

      - name: Copy standalone to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: '.next/standalone/**,.next/static/**,public/**'
          target: '/var/www/vhosts/ratosuryaonline.com/httpdocs'

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/vhosts/ratosuryaonline.com/httpdocs
            pnpm install --prod
