# name: Deploy to Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to Server via SSH
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.DEPLOY_KEY }}
#           passphrase: ${{ secrets.SSH_PASSPHRASE }}
#           script: |
#             cd /var/www/vhosts/ratosuryaonline.com/httpdocs
#             git pull origin main
#             pnpm install
#             pnpm build
#             pm2 restart 0
