name: Build and Deploy Standalone

on:
  push:
    branches:
      - main # or your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js (standalone)
        run: pnpm build

      - name: Copy standalone to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: '.next/standalone/**,.next/static/**,public/**'
          target: '/var/www/vhosts/ratosuryaonline.com/httpdocs'

      - name: Restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/vhosts/ratosuryaonline.com/httpdocs
            pnpm install --prod
